CarPark.Web/Models/Car/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Car
{
    public class AddViewModel
    {

        public int Id { get; set; }

        [Required]
        public string Plate { get; set; }

        [StringLength(50)]
        public string Brand { get; set; }

        [StringLength(50)]
        public string Model { get; set; }



        //other
        //public string DisplayLanguage { get; set; }

        //public string SubmitType { get; set; }
    }
}

CarPark.Web/Models/Car/ListFilterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Car
{
    public class ListFilterViewModel
    {
        public string Filter_Plate { get; set; }
    }
}

CarPark.Web/Models/Car/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Car
{
    public class ListViewModel : ListBaseViewModel<Business.Models.Car.Car, ListFilterViewModel>
    {

    }
}

CarPark.Web/Models/Location/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Location
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }
    }
}

CarPark.Web/Models/Location/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Location
{
    public class ListViewModel : ListBaseViewModel<Business.Models.Location.Location, ListFilterViewModel>
    {
    }
}

CarPark.Web/Models/LocationMove/AddViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.LocationMove
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [Required]
        public int CarId { get; set; }

        [Required]
        public int LocationId { get; set; }

        [Required]
        public DateTime EntryDate { get; set; }

        public DateTime? ExitDate { get; set; }

        //other
        public string Location_Name { get; set; }

        //select List
        public List<SelectListItem> CarSelectList { get; set; }
    }
}

CarPark.Web/Models/Personnel/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Personnel
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [StringLength(20)]
        [Required]
        public string TC { get; set; }

        [StringLength(50)]
        [Required]
        public string Name { get; set; }

        [StringLength(50)]
        [Required]
        public string LastName { get; set; }

        [StringLength(20)]
        [Required]
        public string Phone { get; set; }

        [StringLength(200)]
        [Required]
        public string Address { get; set; }

        [Required]
        [StringLength(50)]
        public string UserName { get; set; }

        [Required]
        [StringLength(150)]
        public string Password { get; set; }
    }
}

CarPark.Web/Models/Personnel/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Personnel
{
    public class ListViewModel : ListBaseViewModel<Business.Models.Personnel.Personnel, ListFilterViewModel>
    {
    }
}

CarPark.Web/Models/Profile/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Profile
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [StringLength(150)]
        public string Code { get; set; }

        [StringLength(150)]
        public string Name { get; set; }

        [Required]
        public int CreatedBy { get; set; }

        [Required]
        public DateTime CreatedDateTime { get; set; }

        public bool IsDeleted { get; set; }
        public DateTime? DeletedDateTime { get; set; }

        public int? DeletedBy { get; set; }
        //edit or delete 
        public string SubmitType { get; set; }
    }
}

CarPark.Web/Models/Profile/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Profile
{
    public class ListViewModel : ListBaseViewModel<CarPark.Web.Business.Models.Profile.Profile, ListFilterViewModel>
    {
    }
}

CarPark.Web/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarPark.Web.Business.Common;
using CarPark.Web.Business.Common.Enums;
using CarPark.Web.Business.Enums;
using CarPark.Web.Business.Interfaces;
using CarPark.Web.Business.Models.Car;
using CarPark.Web.Filters;
using CarPark.Web.Models.Car;
using Microsoft.AspNetCore.Mvc;

namespace CarPark.Web.Controllers
{
    public class CarController : Controller
    {
        private readonly ICarService _carService;
        public CarController(ICarService carService)
        {
            _carService = carService;
        }


        [AppAuthorizeFilter(AuthCodeStatic.PAGE_CAR_LIST)]
        public ActionResult List()
        {
            ListViewModel model = new ListViewModel();

            model.Filter = new ListFilterViewModel();
            model.CurrentPage = 1;
            model.PageSize = 10;
            model.CurrentPage = model.CurrentPage.HasValue ? model.CurrentPage.Value : 1;
            model.PageSize = model.PageSize.HasValue ? model.PageSize.Value : 10;
            model.CurrentLanguageTwoChar = SessionHelper.CurrentLanguageTwoChar;

            var apiResponseModel = _carService.GetAllPaginatedWithDetailBySearchFilter(model.CurrentPage.Value, model.PageSize.Value, model.SortOn, model.SortDirection,model.Filter.Filter_Plate).Result;
            if (apiResponseModel.Status == ResultStatusCodeStatic.Success)
            {
                model.DataList = apiResponseModel.Data;
            }
            else
            {
                ViewBag.ErrorMessage = apiResponseModel.Message;
                return View(model);
            }
            return View(model);
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_CAR_LIST)]
        [HttpPost]
        public ActionResult List(ListViewModel model)
        {
            // filter bilgilerinin default boş değerlerle doldurulması sağlanıyor
            if (model.Filter == null)
            {
                model.Filter = new ListFilterViewModel();
            }

            if (!model.CurrentPage.HasValue)
            {
                model.CurrentPage = 1;
            }

            if (!model.PageSize.HasValue)
            {
                model.PageSize = 10;
            }

            model.CurrentPage = model.CurrentPage.HasValue ? model.CurrentPage.Value : 1;
            model.PageSize = model.PageSize.HasValue ? model.PageSize.Value : 10;

            model.CurrentLanguageTwoChar = SessionHelper.CurrentLanguageTwoChar;

            var apiResponseModel = _carService.GetAllPaginatedWithDetailBySearchFilter(model.CurrentPage.Value, model.PageSize.Value, model.SortOn, model.SortDirection, model.Filter.Filter_Plate).Result;
            if (apiResponseModel.Status == ResultStatusCodeStatic.Success)
            {
                model.DataList = apiResponseModel.Data;
            }
            else
            {
                ViewBag.ErrorMessage = apiResponseModel.Message;
                return View(model);
            }
            return View(model);
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_CAR_ADD)]
        public ActionResult Add()
        {
            Models.Car.AddViewModel model = new AddViewModel();
            return View(model);
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_CAR_ADD)]
        [HttpPost]
        public ActionResult Add(Models.Car.AddViewModel modell)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ErrorMessage = "Error.";
                return View(modell);
            }

            Business.Models.Car.AddRequestModel car = new Business.Models.Car.AddRequestModel();
            car.Plate = modell.Plate;
            car.Brand = modell.Brand;
            car.Model = modell.Model;
            var apiResponseModel = _carService.Add(car).Result;
            if (apiResponseModel.Status == ResultStatusCodeStatic.Success)
            {
                return RedirectToAction(nameof(CarController.List));
            }
            else
            {
                ViewBag.ErrorMessage = apiResponseModel.Message != null ? apiResponseModel.Message : "Kaydedilemedi.";//todo: kulturel olacak NotSaved
                return View(modell);
            }
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_CAR_EDIT)]
        public ActionResult Edit(int id)
        {
            Models.Car.AddViewModel model = new AddViewModel();
            var apiResponseModel = _carService.GetById(id).Result;
            if (apiResponseModel.Status != ResultStatusCodeStatic.Success)
            {
                ViewBag.ErrorMessage = apiResponseModel.Message;
                return View(model);
            }

            var car = apiResponseModel.Data;
            if (car == null)
            {
                return View("_ErrorNotExist");
            }

            model.Id = car.Id;
            model.Plate = car.Plate;
            model.Brand = car.Brand;
            model.Model = car.Model;
            return View(model);
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_CAR_EDIT)]
        [HttpPost]
        public ActionResult Edit(Models.Car.AddViewModel modell)
        {
            if (!ModelState.IsValid)
            {
                return View(modell);
            }

            var apiResponseModel = _carService.GetById(modell.Id).Result;
            if (apiResponseModel.Status != ResultStatusCodeStatic.Success)
            {
                ViewBag.ErrorMessage = apiResponseModel.Message;
                return View(modell);
            }

            var car = apiResponseModel.Data;

            if (car == null)
            {
                return View("_ErrorNotExist");
            }

            AddRequestModel editModel = new AddRequestModel();
            editModel.Id = car.Id;
            editModel.Plate = modell.Plate;
            editModel.Brand = modell.Brand;
            editModel.Model = modell.Model;

           
                var apiEditResponseModel = _carService.Edit(modell.Id, editModel).Result;
                if (apiEditResponseModel.Status != ResultStatusCodeStatic.Success)
                {
                    ViewBag.ErrorMessage = apiEditResponseModel.Message != null ? apiEditResponseModel.Message : "Not Edited";
                    return View(modell);
                }
           
            return RedirectToAction(nameof(CarController.List));
        }
    }
}

CarPark.Web/Views/Car/Add.cshtml
@using CarPark.Web.Business.Common
@using CarPark.Web.Controllers

@model CarPark.Web.Models.Car.AddViewModel

@{
    ViewData["Title"] = "Car Add";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Car Add</strong>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Add", "Car", FormMethod.Post, new { @class = "form-horizontal input-sm" }))
                {

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Plate</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Plate, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Plate, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>


                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Brand</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Brand, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Brand, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Model</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Model, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Model, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <button class="btn btn-sm btn-primary" type="submit" id="btnSubmit">
                                <i class="fa fa-dot-circle-o"></i> Save
                            </button>
                            &nbsp;
                            <a class="btn btn-sm btn-danger" href="~/Car/List">
                                <i class="fa fa-ban"></i> Cancel
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">

                            @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                            {
                                <div class="text-danger">
                                    @ViewBag.ErrorMessage
                                </div>
                            }
                            @if (ViewBag.ErrorMessageList != null)
                            {
                                <div class="text-danger">
                                    @foreach (var item in ViewBag.ErrorMessageList)
                                    {
                                        <span>@item</span>
                                        <br />
                                    }
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

CarPark.Web/Views/Car/Edit.cshtml
@using CarPark.Web.Business.Common
@using CarPark.Web.Controllers
@model CarPark.Web.Models.Car.AddViewModel

@{
    ViewData["Title"] = "Car Edit";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong> Car Edit </strong>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Edit", "Car", FormMethod.Post, new { @class = "form-horizontal input-sm" }))
                {
                    @Html.HiddenFor(m => m.Id)
                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Plate</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Plate, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Plate, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Brand</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Brand, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Brand, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Model</label>
                        <div class="col-md-9">
                            @Html.TextBoxFor(m => m.Model, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(m => m.Model, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <button class="btn btn-sm btn-primary" type="submit" id="btnSubmit" name="SubmitType" value="Edit">
                                <i class="fa fa-dot-circle-o"></i>Save
                            </button>
                            &nbsp;
                            &nbsp;
                            <button class="btn btn-sm btn-secondary" type="submit" name="SubmitType" value="Delete" onclick="return confirm('Are You Sure?');">
                                <i class="fa fa-trash"></i>  Delete
                            </button>


                            &nbsp;
                            &nbsp;
                            <a class="btn btn-sm btn-danger" href="~/Car/List">
                                <i class="fa fa-ban"></i> Cancel
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">

                            @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                            {
                                <div class="text-danger">
                                    @ViewBag.ErrorMessage
                                </div>
                            }
                            @if (ViewBag.ErrorMessageList != null)
                            {
                                <div class="text-danger">
                                    @foreach (var item in ViewBag.ErrorMessageList)
                                    {
                                        <span>@item</span>
                                        <br />
                                    }
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

CarPark.Web/Views/Car/List.cshtml
@using CarPark.Web.Business.Common
@using CarPark.Web.Business.Enums
@using CarPark.Web.Controllers

@model CarPark.Web.Models.Car.ListViewModel

@{
    ViewData["Title"] = "Car List";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Car List

                @if (SessionHelper.CheckAuthForCurrentUser(AuthCodeStatic.PAGE_CAR_ADD))
                {
                    <span>- </span><a class="btn btn-sm btn-primary" href="~/Car/Add"> New Record</a>
                }
            </div>
            <div class="card-body">

                <div class="row">
                    <div class="col-lg-12">

                        @using (Html.BeginForm("List", "Car", FormMethod.Post, new { @class = "form-horizontal input-sm", @id = "filterForm" }))
                        {
                            <!-- form get'te submit yapilirken page bilgisi ve siralama bilgisinin tutulmasi icin -->
                            @Html.HiddenFor(m => m.PageSize, new { @id = "hiddenPageSize" });
                            @Html.HiddenFor(m => m.CurrentPage, new { @id = "hiddenCurrentPage" });
                            @Html.HiddenFor(m => m.SortOn, new { @id = "hiddenSortOn" })
                            @Html.HiddenFor(m => m.SortDirection, new { @id = "hiddenSortDirection" })

                            <div class="form-group row">
                                <label class="col-md-2 col-form-label">Plate </label>
                                <div class="col-md-9">
                                    @Html.TextBoxFor(m => m.Filter.Filter_Plate, new { @class = "form-control form-control-sm" })
                                    @Html.ValidationMessageFor(m => m.Filter.Filter_Plate, null, new { @class = "help-block text-danger" })
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-12">
                                    <button class="btn btn-sm btn-primary" type="submit" name="SubmitType" value="List">
                                        <i class="fa fa-search"></i> List
                                    </button>
                                    <hr />
                                </div>
                            </div>
                        }

                    </div>
                </div>

                <div class="text-left small">
                    Total Count: @Model.DataList.TotalCount Displaying Records: @Model.DataList.From - @Model.DataList.To
                    <div class="float-right">
                        <span>Page Size:</span> @Html.TextBox("txtPageSize", "", new { @class = "form-control form-control-sm d-inline-block onlyNumberEntry", @id = "txtPageSize", @style = " width:50px; height:calc(1.5em + 0.5rem - 2px);" })
                    </div>
                </div>

                <div class="table-responsive">
                    <table class="table table-responsive-sm table-bordered table-striped table-sm">
                        <thead>
                            <tr>
                                @if (SessionHelper.CheckAuthForCurrentUser(AuthCodeStatic.PAGE_CAR_EDIT))
                                {
                                    <th>*</th>
                                }
                                <th>
                                    <a href="javascript:void(0)" onclick="ClickSorting('Plate','@(Model.DataList.SortDirection == "ASC" ? "DESC" : "ASC")')">
                                        Plate
                                        @if (Model.DataList.SortOn == "Plate")
                                        {
                                            if (Model.DataList.SortDirection == "ASC")
                                            {<i class="fa fa-angle-up"></i> }
                                            else
                                            { <i class="fa fa-angle-down"></i>}
                                        }
                                    </a>
                                </th>

                                <th>
                                    <a href="javascript:void(0)" onclick="ClickSorting('Brand','@(Model.DataList.SortDirection == "ASC" ? "DESC" : "ASC")')">
                                        Brand
                                        @if (Model.DataList.SortOn == "Brand")
                                        {
                                            if (Model.DataList.SortDirection == "ASC")
                                            {<i class="fa fa-angle-up"></i> }
                                            else
                                            { <i class="fa fa-angle-down"></i>}
                                        }
                                    </a>
                                </th>

                                <th>
                                    <a href="javascript:void(0)" onclick="ClickSorting('Model','@(Model.DataList.SortDirection == "ASC" ? "DESC" : "ASC")')">
                                        Model
                                        @if (Model.DataList.SortOn == "Model")
                                        {
                                            if (Model.DataList.SortDirection == "ASC")
                                            {<i class="fa fa-angle-up"></i> }
                                            else
                                            { <i class="fa fa-angle-down"></i>}
                                        }
                                    </a>
                                </th>


                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model.DataList.Items)
                            {
                            <tr>

                                @if (SessionHelper.CheckAuthForCurrentUser(AuthCodeStatic.PAGE_CAR_EDIT))
                                {
                                    <td>
                                        <a class="btn btn-sm btn-danger" href="~/Car/Edit/@item.Id">Edit</a>
                                    </td>
                                }

                                <td>@item.Plate</td>
                                <td>@item.Brand</td>
                                <td>@item.Model</td>
                            </tr>
                            }

                        </tbody>
                    </table>

                </div>


                <nav>

                    @await Html.PartialAsync("_PagingPartial", Model)
                </nav>

                @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                {
                    <div class="text-danger">
                        @ViewBag.ErrorMessage
                    </div>
                }
                @if (ViewBag.ErrorMessageList != null)
                {
                    <div class="text-danger">
                        @foreach (var item in ViewBag.ErrorMessageList)
                        {
                            <span>@item</span>
                            <br />
                        }
                    </div>
                }

            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

@section Scripts {
    <!-- pagesize ve current page js  -->
    <script>
        $(document).ready(function(){
            $('#txtPageSize').keyup(function () {
                $('#hiddenPageSize').val($('#txtPageSize').val());
            });

            $('#txtPageSize').val(@((Model.PageSize)));

            $('#txtCurrentPage').keyup(function () {
                $('#hiddenCurrentPage').val($('#txtCurrentPage').val());
            });

            $('#txtCurrentPage').val(@((Model.CurrentPage)));

            $(".onlyNumberEntry").keypress(function (e) {
                if (e.which == 13) {
                    $('#filterForm').submit();
                }
                if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
                }
            });
        }); // end of $(document).ready


        function ClickSorting(sortOn, sortDirection) {
            $('#hiddenSortOn').val(sortOn);
            $('#hiddenSortDirection').val(sortDirection);
            //$("#btnSorting").click();
            $('#filterForm').submit();
        }

        function ClickPaging(currentPage, pageSize) {
            $('#hiddenCurrentPage').val(currentPage);
            $('#hiddenPageSize').val(pageSize);
            //$("#btnPaging").click();
            $('#filterForm').submit();
        }
    </script>

}

CarPark.Web/Views/Car/_PagingPartial.cshtml
@using CarPark.Web.Business.Common
@model CarPark.Web.Models.Car.ListViewModel

<ul class="pagination pagination-sm">
    @if (Model.DataList.HasPreviousPage)
    {
        <li class="page-item">
            <a class="page-link btn-info" href="javascript:void(0)" onclick="ClickPaging('@(Model.DataList.CurrentPage-1)','@Model.DataList.PageSize')"> Previous </a>
        </li>
    }

    @for (int paginationIndex = Model.DataList.CurrentPage - 3; paginationIndex < Model.DataList.CurrentPage; paginationIndex++)
    {
        if (paginationIndex <= 0)
        {
            continue;
        }

        <li class="page-item">
            <a class="page-link" href="javascript:void(0)" onclick="ClickPaging('@(paginationIndex)','@Model.DataList.PageSize')">@(paginationIndex)</a>
        </li>
    }

    <li class="page-item active">
        <a class="page-link" href="javascript:void(0)" onclick="ClickPaging('@(Model.DataList.CurrentPage)','@Model.DataList.PageSize')">@(Model.DataList.CurrentPage)</a>
    </li>

    @for (int paginationIndex = Model.DataList.CurrentPage + 1; paginationIndex < Model.DataList.TotalPages + 1; paginationIndex++)
    {
        if (paginationIndex > Model.DataList.TotalPages || paginationIndex > (Model.DataList.CurrentPage + 3))
        {
            break;
        }

        <li class="page-item">
            <a class="page-link" href="javascript:void(0)" onclick="ClickPaging('@(paginationIndex)','@Model.DataList.PageSize')">@(paginationIndex)</a>
        </li>
    }

    @if (Model.DataList.HasNextPage)
    {
        <li class="page-item">
            <a class="page-link btn-info" href="javascript:void(0)" onclick="ClickPaging('@(Model.DataList.CurrentPage+1)','@Model.DataList.PageSize')">Next</a>
        </li>
    }

    <li class="page-item">
        <span class="small">&nbsp;Current Size</span> @Html.TextBox("txtCurrentPage", "", new { @class = "form-control form-control-sm d-inline-block onlyNumberEntry", @id = "txtCurrentPage", @style = "width:60px; height:calc(1.5em + 0.5rem - 2px); " })
    </li>

    <li class="page-item">
        <span class="small">&nbsp; Total Pages: @Model.DataList.TotalPages </span>
    </li>

</ul>