CarPark.Web/Models/Car/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Car
{
    public class AddViewModel
    {

        public int Id { get; set; }

        [Required]
        public string Plate { get; set; }

        [StringLength(50)]
        public string Brand { get; set; }

        [StringLength(50)]
        public string Model { get; set; }



        //other
        //public string DisplayLanguage { get; set; }

        //public string SubmitType { get; set; }
    }
}

CarPark.Web/Models/Car/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Car
{
    public class ListViewModel : ListBaseViewModel<Business.Models.Car.Car, ListFilterViewModel>
    {

    }
}

CarPark.Web/Models/Location/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Location
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }
    }
}

CarPark.Web/Models/Location/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Location
{
    public class ListViewModel : ListBaseViewModel<Business.Models.Location.Location, ListFilterViewModel>
    {
    }
}

CarPark.Web/Models/LocationMove/AddViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.LocationMove
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [Required]
        public int CarId { get; set; }

        [Required]
        public int LocationId { get; set; }

        [Required]
        public DateTime EntryDate { get; set; }

        public DateTime? ExitDate { get; set; }

        //other
        public string Location_Name { get; set; }

        //select List
        public List<SelectListItem> CarSelectList { get; set; }
    }
}

CarPark.Web/Models/Personnel/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Personnel
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [StringLength(20)]
        [Required]
        public string TC { get; set; }

        [StringLength(50)]
        [Required]
        public string Name { get; set; }

        [StringLength(50)]
        [Required]
        public string LastName { get; set; }

        [StringLength(20)]
        [Required]
        public string Phone { get; set; }

        [StringLength(200)]
        [Required]
        public string Address { get; set; }

        [Required]
        [StringLength(50)]
        public string UserName { get; set; }

        [Required]
        [StringLength(150)]
        public string Password { get; set; }
    }
}

CarPark.Web/Models/Personnel/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Personnel
{
    public class ListViewModel : ListBaseViewModel<Business.Models.Personnel.Personnel, ListFilterViewModel>
    {
    }
}

CarPark.Web/Models/Profile/AddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Profile
{
    public class AddViewModel
    {
        public int Id { get; set; }

        [StringLength(150)]
        public string Code { get; set; }

        [StringLength(150)]
        public string Name { get; set; }

        [Required]
        public int CreatedBy { get; set; }

        [Required]
        public DateTime CreatedDateTime { get; set; }

        public bool IsDeleted { get; set; }
        public DateTime? DeletedDateTime { get; set; }

        public int? DeletedBy { get; set; }
        //edit or delete 
        public string SubmitType { get; set; }
    }
}

CarPark.Web/Models/Profile/ListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.Profile
{
    public class ListViewModel : ListBaseViewModel<CarPark.Web.Business.Models.Profile.Profile, ListFilterViewModel>
    {
    }
}

CarPark.Web/Controllers/LocationMoveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarPark.Web.Business.Common.Enums;
using CarPark.Web.Business.Enums;
using CarPark.Web.Business.Interfaces;
using CarPark.Web.Business.Models.LocationMove;
using CarPark.Web.Filters;
using CarPark.Web.Models.LocationMove;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarPark.Web.Controllers
{
    public class LocationMoveController : Controller
    {
        private readonly ILocationMoveService _locationMoveService;
        private readonly ICarService _carService;

        public LocationMoveController(ILocationMoveService locationMoveService, ICarService carService )
        {
            _locationMoveService = locationMoveService;
            _carService = carService;
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_LOCATIONMOVE_LIST)]
        public IActionResult List()
        {
            List<LocationWithDetail> model = new List<LocationWithDetail>();
            var apiResponseModel = _locationMoveService.GetAllWithDetail().Result;
            if (apiResponseModel.Status == ResultStatusCodeStatic.Success)
            {
                model = apiResponseModel.Data;
            }
            else
            {
                ViewBag.ErrorMessage = apiResponseModel.Message;
                return View(model);
            }
            return View(model);
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_LOCATIONMOVE_LIST)]
        public ActionResult Add(int locationId)
        {
            if (locationId <= 0)
            {
                return View("_ErrorNotExist");
            }
            Models.LocationMove.AddViewModel model = new AddViewModel();
            var apiResponseModel = _locationMoveService.GetLocationByLocationIdWithDetail(locationId).Result;
            if (apiResponseModel.Status == ResultStatusCodeStatic.Success)
            {
                //not error
            }
            else
            {
                ViewBag.ErrorMessage = apiResponseModel.Message;
                return View(model);
            }

            var roomWithDetail = apiResponseModel.Data;
            if (roomWithDetail.IsEmpty == false)
            {
                return View("_ErrorNotExist");
            }
            model.LocationId = roomWithDetail.LocationId;

            //select list
            model.CarSelectList = GetCarSelectList();
            return View(model);
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_LOCATIONMOVE_LIST)]
        [HttpPost]
        public ActionResult Add(Models.LocationMove.AddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.CarSelectList = GetCarSelectList();
                return View(model);
            }
            var apiResponseModel = _locationMoveService.GetLocationByLocationIdWithDetail(model.LocationId).Result;
            if (apiResponseModel.Status == ResultStatusCodeStatic.Success)
            {
                //not error
            }
            else
            {
                ViewBag.ErrorMessage = apiResponseModel.Message;
                return View(model);
            }
            var locationMove = apiResponseModel.Data;
            if (locationMove.IsEmpty == false)
            {
                return View("_ErrorNotExist");
            }

            AddRequestModel record = new AddRequestModel();
            record.CarId = model.CarId;
            record.LocationId = locationMove.LocationId;
            record.EntryDate = DateTime.Now;
            var apiResult = _locationMoveService.Add(record).Result;
            if (apiResult.Status == ResultStatusCodeStatic.Success)
            {
                //not error
            }
            else
            {
                ViewBag.ErrorMessage = apiResult.Message;
                return View(model);
            }
            var result = apiResult.Data;
            if (result.Id > 0)
            {
                return RedirectToAction(nameof(LocationMoveController.List));
            }
            else
            {
                ViewBag.ErrorMessage = "Not Saved";
                model.CarSelectList = GetCarSelectList();
                return View(model);
            }
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_LOCATIONMOVE_LIST)]
        public ActionResult Edit(int locationId)
        {
            if (locationId <= 0)
            {
                return View("_ErrorNotExist");
            }
            Models.LocationMove.AddViewModel model = new AddViewModel();
            var locationWithDetail = _locationMoveService.GetLocationByLocationIdWithDetail(locationId).Result.Data;
            if (locationWithDetail.IsEmpty == true)
            {
                return View("_ErrorNotExist");
            }

            var locationMoveResponce = _locationMoveService.GetById(locationWithDetail.LocationMove_ID).Result.Data;
            if (locationMoveResponce == null)
            {
                return View("_ErrorNotExist");
            }
            model.CarId = locationMoveResponce.CarId;
            model.LocationId = locationMoveResponce.LocationId;
            model.EntryDate = locationMoveResponce.EntryDate;
            model.ExitDate = locationMoveResponce.ExitDate;
            model.Id = locationMoveResponce.Id;
            model.Location_Name = locationWithDetail.LocationName;

            model.CarSelectList = GetCarSelectList();
            return View(model);
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_LOCATIONMOVE_LIST)]
        [HttpPost]
        public ActionResult Edit(Models.LocationMove.AddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.CarSelectList = GetCarSelectList();
                return View(model);
            }

            var locationMove = _locationMoveService.GetById(model.Id).Result.Data;
            if (locationMove.ExitDate != null)
            {
                return View("_ErrorNotExist");
            }

            AddRequestModel addRequestModel = new AddRequestModel();
            addRequestModel.Id = locationMove.Id;
            addRequestModel.CarId = locationMove.CarId;
            addRequestModel.LocationId = locationMove.LocationId;
            addRequestModel.EntryDate = locationMove.EntryDate;
            addRequestModel.ExitDate = DateTime.Now;

            var result = _locationMoveService.Edit(model.Id, addRequestModel).Result;
            if (result.Status != ResultStatusCodeStatic.Success)
            {
                ViewBag.ErrorMessage = "Not Edited";
                model.CarSelectList = GetCarSelectList();

                return View(model);
            }
            return RedirectToAction(nameof(LocationMoveController.List));
        }


        [NonAction]
        private List<SelectListItem> GetCarSelectList()
        {
            //müşteri kayıtları listelenir
            List<SelectListItem> resultList = new List<SelectListItem>();
            resultList = _locationMoveService.GetAllCarWhichIsNotLocationMove().Result.Data.OrderBy(r => r.Plate).Select(r => new SelectListItem() { Value = r.Id.ToString(), Text = r.Plate }).ToList();
            return resultList;
        }
    }
}

CarPark.Web/Views/LocationMove/Add.cshtml
@using CarPark.Web.Business.Common
@using CarPark.Web.Controllers

@model CarPark.Web.Models.LocationMove.AddViewModel

@{
    ViewData["Title"] = "Location Move Add";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong>Location Move Add</strong>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Add", "LocationMove", FormMethod.Post, new { @class = "form-horizontal input-sm" }))
                {
                    @Html.HiddenFor(m => m.LocationId);


                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Car</label>
                        <div class="col-md-9">
                            @Html.DropDownListFor(m => m.CarId, Model.CarSelectList, "Select", new { @class = "form-control form-control-sm", @id = "cbCar" })
                            @Html.ValidationMessageFor(m => m.CarId, null, new { @class = "help-block text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <button class="btn btn-sm btn-primary" type="submit" id="btnSubmit">
                                <i class="fa fa-dot-circle-o"></i> ENTRY
                            </button>
                            &nbsp;
                            <a class="btn btn-sm btn-danger" href="~/LocationMove/List">
                                <i class="fa fa-ban"></i> Cancel
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">

                            @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                            {
                                <div class="text-danger">
                                    @ViewBag.ErrorMessage
                                </div>
                            }
                            @if (ViewBag.ErrorMessageList != null)
                            {
                                <div class="text-danger">
                                    @foreach (var item in ViewBag.ErrorMessageList)
                                    {
                                        <span>@item</span>
                                        <br />
                                    }
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

CarPark.Web/Views/LocationMove/Edit.cshtml
@using CarPark.Web.Business.Common
@using CarPark.Web.Controllers
@model CarPark.Web.Models.LocationMove.AddViewModel

@{
    ViewData["Title"] = "Location Move Edit";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <strong> Location Move Edit </strong>
            </div>
            <div class="card-body">

                @using (Html.BeginForm("Edit", "LocationMove", FormMethod.Post, new { @class = "form-horizontal input-sm" }))
                {
                    @Html.HiddenFor(m => m.Id)
                    @Html.HiddenFor(m => m.CarId)
                    @Html.HiddenFor(m => m.LocationId)
                   

                    <div class="form-group row">
                        <label class="col-md-2 col-form-label">Location</label>
                        <div class="col-md-9">
                            @Model.Location_Name
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <button class="btn btn-sm btn-primary" type="submit" id="btnSubmit" name="SubmitType" value="Edit">
                                <i class="fa fa-dot-circle-o"></i>RELEASE
                            </button>

                            &nbsp;
                            <a class="btn btn-sm btn-danger" href="~/LocationMove/List">
                                <i class="fa fa-ban"></i> Cancel
                            </a>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">

                            @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                            {
                                <div class="text-danger">
                                    @ViewBag.ErrorMessage
                                </div>
                            }
                            @if (ViewBag.ErrorMessageList != null)
                            {
                                <div class="text-danger">
                                    @foreach (var item in ViewBag.ErrorMessageList)
                                    {
                                        <span>@item</span>
                                        <br />
                                    }
                                </div>
                            }

                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

CarPark.Web/Views/LocationMove/List.cshtml
@using CarPark.Web.Business.Common
@using CarPark.Web.Business.Enums
@using CarPark.Web.Controllers

@model List<CarPark.Web.Business.Models.LocationMove.LocationWithDetail>

@{
    ViewData["Title"] = "Location Move List";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i>  Location Move List
            </div>
            <div class="card-body">

                <div class="row text-center center-block d-flex ">

                    @foreach (var item in Model)
                    {
                        @if (item.IsEmpty)
                        {

                            <div class="col-md-3 text-center align-center  d-flex justify-content-center align-items-center" style="background-color:green; height:130px; border:solid 10px white;" onclick="location.href ='@Url.Action("Add", "LocationMove", new { locationId =@item.LocationId })'">
                                <b style="color:white;"> @item.LocationName</b>
                            </div>

                        }
                        else
                        {

                            <div class="col-md-3 text-center align-center  d-flex justify-content-center align-items-center" style="background-color:red; height:130px; border:solid 10px white; " onclick="location.href ='@Url.Action("Edit", "LocationMove", new { locationId =@item.LocationId })'">
                                <b style="color:white;">  @item.LocationName</b>
                            </div>

                        }
                    }


                </div>


                @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                {
                    <div class="text-danger">
                        @ViewBag.ErrorMessage
                    </div>
                }
                @if (ViewBag.ErrorMessageList != null)
                {
                    <div class="text-danger">
                        @foreach (var item in ViewBag.ErrorMessageList)
                        {
                            <span>@item</span>
                            <br />
                        }
                    </div>
                }

            </div>
        </div>
    </div>
    <!-- /.col-->
</div>

CarPark.Web/Views/LocationMove/_ErrorNotExist.cshtml
@using CarPark.Web.Business.Common

@{
    ViewBag.Title = "Error Not Exist";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">

        <div class="card">
            <div class="card-header">
                <strong>@ViewBag.Title</strong>
            </div>
            <div class="card-body">
                Error Not Exist Record
            </div>
        </div>

    </div>
</div>