CarPark.Web/Models/ProfileDetail/AuthCheckViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.ProfileDetail
{
    public class AuthCheckViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Checked { get; set; }
        public string Code { get; set; }
    }
}

CarPark.Web/Models/ProfileDetail/BatchEditViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.ProfileDetail
{
    public class BatchEditViewModel
    {
        public int? ProfileId { get; set; }
        public List<SelectListItem> ProfileSelectList { get; set; }

        public List<AuthCheckViewModel> AuthList { get; set; }
        public List<AuthCheckViewModel> AuthWhichIsNotIncludeList { get; set; }

        public string SubmitType { get; set; }
    }
}

CarPark.Web/Models/ProfilePersonnel/BatchEditViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarPark.Web.Models.ProfilePersonnel
{
    public class BatchEditViewModel
    {
        public int? ProfileId { get; set; }
        public List<SelectListItem> ProfileSelectList { get; set; }
        public DefinedPersonnelListViewModel PersonnelList { get; set; }
        public UndefinedPersonnelListViewModel PersonnelWhichIsNotIncludeList { get; set; }

        public string SubmitType { get; set; }
    }
}

CarPark.Web/Controllers/ProfileDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarPark.Web.Business.Common;
using CarPark.Web.Business.Common.Enums;
using CarPark.Web.Business.Enums;
using CarPark.Web.Business.Interfaces;
using CarPark.Web.Business.Models.ProfileDetail;
using CarPark.Web.Filters;
using CarPark.Web.Models.ProfileDetail;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarPark.Web.Controllers
{
    public class ProfileDetailController : Controller
    {
        private readonly IProfileDetailService _profileDetailService;
        private readonly IProfileService _profileService;

        public ProfileDetailController(IProfileDetailService profileDetailService, IProfileService profileService)
        {
            _profileDetailService = profileDetailService;
            _profileService = profileService;
        }

        [AppAuthorizeFilter(AuthCodeStatic.PAGE_PROFILEDETAIL_BATCHEDIT)]
        public ActionResult BatchEdit()
        {
            BatchEditViewModel model = new BatchEditViewModel();
            model.ProfileSelectList = GetProfileSelectList();
            model.AuthList = new List<AuthCheckViewModel>();
            model.AuthWhichIsNotIncludeList = new List<AuthCheckViewModel>();
            return View(model);
        }

        [HttpPost]
        [AppAuthorizeFilter(AuthCodeStatic.PAGE_PROFILEDETAIL_BATCHEDIT)]
        public ActionResult BatchEdit(BatchEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                if (model.ProfileId.HasValue)
                {
                    model.AuthList = GetAllAuthByProfileId(model.ProfileId.Value);
                    model.AuthWhichIsNotIncludeList = GetAllAuthByProfileIdWhichIsNotIncluded(model.ProfileId.Value);
                }
                else
                {
                    model.AuthList = new List<AuthCheckViewModel>();
                    model.AuthWhichIsNotIncludeList = new List<AuthCheckViewModel>();
                }
                return View(model);
            }

            if (model.SubmitType == "Add")
            {
                if (model.AuthWhichIsNotIncludeList != null)
                {
                    ModelState.Clear();
                    List<AuthCheckViewModel> record = model.AuthWhichIsNotIncludeList.Where(x => x.Checked == true).ToList();
                    if (record != null)
                    {
                        foreach (var item in record)
                        {
                            AddRequestModel profileDetail = new AddRequestModel();
                            profileDetail.AuthId = item.Id;
                            profileDetail.ProfileId = model.ProfileId.Value;
                            var result = _profileDetailService.Add(profileDetail).Result;
                        }
                    }
                }
            }
            if (model.SubmitType == "Delete")
            {
                if (model.AuthList != null)
                {
                    ModelState.Clear();
                    List<AuthCheckViewModel> record = model.AuthList.Where(x => x.Checked == true).ToList();
                    if (record != null)
                    {
                        foreach (var item in record)
                        {
                            var apiResponseModel = _profileDetailService.Delete(model.ProfileId.Value, item.Id).Result;
                            if (apiResponseModel.Status == ResultStatusCodeStatic.Success)
                            {
                                //not error
                            }
                            else
                            {
                                BatchEditViewModel batchEditViewModel = new BatchEditViewModel();

                                batchEditViewModel.ProfileSelectList = GetProfileSelectList();


                                batchEditViewModel.AuthList = GetAllAuthByProfileId( model.ProfileId.Value);
                                batchEditViewModel.AuthWhichIsNotIncludeList = GetAllAuthByProfileIdWhichIsNotIncluded( model.ProfileId.Value);
                                ViewBag.ErrorMessage = apiResponseModel.Message;
                                return View(batchEditViewModel);
                            }
                        }
                    }
                }
            }


            model.ProfileSelectList = GetProfileSelectList();
            if (model.ProfileId.HasValue)
            {
                model.AuthList = GetAllAuthByProfileId(model.ProfileId.Value);
                model.AuthWhichIsNotIncludeList = GetAllAuthByProfileIdWhichIsNotIncluded( model.ProfileId.Value);
            }
            else
            {
                model.AuthList = new List<AuthCheckViewModel>();
                model.AuthWhichIsNotIncludeList = new List<AuthCheckViewModel>();
            }
            return View(model);
        }

        [NonAction]
        private List<AuthCheckViewModel> GetAllAuthByProfileId(int profileId)
        {
            //profile ait yetki kayıtları listelenir
            List<AuthCheckViewModel> resultList = new List<AuthCheckViewModel>();
            resultList = _profileDetailService.GetAllAuthByProfileId(profileId).Result.Data.Select(a => new AuthCheckViewModel() { Id = a.Id, Name = a.Name, Checked = false, Code = a.Code }).ToList();
            return resultList;
        }

        [NonAction]
        private List<AuthCheckViewModel> GetAllAuthByProfileIdWhichIsNotIncluded(int profileId)
        {
            //profile ait olmayan yetki kayıtları listelenir
            List<AuthCheckViewModel> resultList = new List<AuthCheckViewModel>();
            resultList = _profileDetailService.GetAllAuthByProfileIdWhichIsNotIncluded(profileId).Result.Data.Select(a => new AuthCheckViewModel() { Id = a.Id, Name = a.Name, Checked = false, Code = a.Code }).ToList();
            return resultList;
        }

        [NonAction]
        private List<SelectListItem> GetProfileSelectList()
        {
            // aktif profil kayıtları listelenir
            List<SelectListItem> resultList = new List<SelectListItem>();
            resultList = _profileService.GetAll().Result.Data.OrderBy(r => r.Name).Select(r => new SelectListItem() { Value = r.Id.ToString(), Text = r.Name }).ToList();
            return resultList;
        }
    }
}

CarPark.Web/Views/ProfileDetail/BatchEdit.cshtml
@using CarPark.Web.Business.Common
@using CarPark.Web.Controllers

@model CarPark.Web.Models.ProfileDetail.BatchEditViewModel
@{
    ViewData["Title"] = "Batch Edit";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Profile Detail - Batch Edit
            </div>
            <div class="card-body">
                @using (Html.BeginForm("BatchEdit", "ProfileDetail", FormMethod.Post, new { @class = "form-horizontal input-sm", @id = "batchEditForm" }))
                {
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group row">
                                <div class="col-md-3"></div>
                                <label class="col-md-1 col-form-label">Profile </label>
                                <div class="col-md-3" id="dvProfileCombobox">
                                    @Html.DropDownListFor(m => m.ProfileId, Model.ProfileSelectList, "Select", new { @class = "form-control form-control-sm", @id = "cbProfile" })
                                </div>
                            </div>
                            <hr />
                        </div>
                    </div>
                    @Html.HiddenFor(m => m.ProfileId)
                    <div class="row">

                        <div class="col-md-5 p-0 m-0" style="border:#8B8B8B solid 1px;padding-bottom:2px; padding-top:2px;">
                            <div class="text-center">
                                <strong>
                                    <label style="margin-top:0.5em;margin-bottom:0px;">Undefined Authorizations</label>
                                </strong>
                                <hr />
                            </div>

                            <div style="height:330px; overflow-y: scroll;margin-bottom:2px;">
                                <table class="table table-responsive-sm table-bordered table-striped table-sm table-hover">
                                    <thead>
                                        <tr>
                                            <th> * </th>
                                            <th>Name</th>
                                            <th>Code</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @for (var i = 0; i < Model.AuthWhichIsNotIncludeList.Count(); i++)
                                        {

                                            <tr>
                                                <td>
                                                    @Html.CheckBoxFor(it => it.AuthWhichIsNotIncludeList[i].Checked)
                                                </td>
                                                <td>
                                                    @Html.HiddenFor(it => it.AuthWhichIsNotIncludeList[i].Id)
                                                    @Html.DisplayFor(it => it.AuthWhichIsNotIncludeList[i].Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(it => it.AuthWhichIsNotIncludeList[i].Code)
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                        </div>

                        <div class=" col-md-2 text-center align-self-center  p-0 m-0 ">

                            <div class="mb-1">
                                <button class="btn btn-sm btn-primary" type="submit" id="btnSubmit" name="SubmitType" value="Add">
                                    <i class="fa fa-angle-double-right fa-2x"></i>Add
                                </button>

                            </div>

                            <div class="mt-1">
                                <button class="btn btn-sm btn-danger" type="submit" id="btnSubmit" name="SubmitType" value="Delete">
                                    <i class="fa fa-angle-double-left fa-2x"></i>Delete
                                </button>

                            </div>

                        </div>

                        <div class="col-md-5 p-0 m-0" style="border:#8B8B8B solid 1px;padding-bottom:2px; padding-top:2px;">
                            <div class="text-center">
                                <strong>
                                    <label style="margin-top:0.5em;margin-bottom:0px;">Defined Authorizations</label>
                                </strong>
                                <hr />
                            </div>

                            <div style="height:330px; overflow-y: scroll;margin-bottom:2px;">
                                <table class="table table-responsive-sm table-bordered table-striped table-sm table-hover">
                                    <thead>
                                        <tr>
                                            <th> * </th>
                                            <th> Name</th>
                                            <th> Code</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @for (var i = 0; i < Model.AuthList.Count(); i++)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.CheckBoxFor(it => it.AuthList[i].Checked)
                                                </td>
                                                <td>
                                                    @Html.HiddenFor(it => it.AuthList[i].Id)
                                                    @Html.DisplayFor(it => it.AuthList[i].Name)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(it => it.AuthList[i].Code)
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>

                    <div class="form-group row">
                        @if (ViewBag.ErrorMessage != null && !string.IsNullOrEmpty(ViewBag.ErrorMessage))
                        {
                            <div class="text-danger">
                                @ViewBag.ErrorMessage
                            </div>
                        }
                        @if (ViewBag.ErrorMessageList != null)
                        {
                            <div class="text-danger">
                                @foreach (var item in ViewBag.ErrorMessageList)
                                {
                                    <span>@item</span>
                                    <br />
                                }
                            </div>
                        }

                    </div>
                }
            </div>
        </div>
    </div>

    @section Scripts {
        <script>
            var selectString = 'Select';
            $(document).ready(function () {
                $('#cbProfile').change(function () {
                    if ($('#cbProfile').val() != '') {
                        $('#batchEditForm').submit();
                    }
                });
            });
        </script>
    }